name: Build And Test
on: [push, pull_request]
jobs:
  plugin:
    name: Plugin (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [7.1]
        wp-version: [5.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: My first step
        uses: ./.github/actions/build-wp-container
      - name: Build
        run: |
          pwd
          ls
          npm -v
