name: Build And Test
on: [push, pull_request]
jobs:
  plugin:
    name: Plugin (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [7.3]
        wp-version: [5.5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create WP Server
        uses: ./.github/actions/build-wp-container
        with:
          args: |
            PHP_VERSION=${{ matrix.php-version }}
            WP_VERSION=${{ matrix.wp-version }}
      - name: Build
        run: |
          pwd
          ls
          npm -v
