name: Build And Test
on: [push, pull_request]
jobs:
  plugin:
    name: Plugin (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [7.3]
        wp-version: [5.25]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container
        uses: docker/build-push-action@v2
        with:
          file: .github/actions/build-wp-container
          push: false
          build-args: |
            PHP_VERSION=${{ matrix.php-version }}
            WP_VERSION=${{ matrix.wp-version }}
      - name: Build
        run: |
          pwd
          ls
          npm -v
