name: Build And Test
on: [push, pull_request]
jobs:
  plugin:
    name: Plugin (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [7.3]
        wp-version: [5.5]
    services:
        mysql:
            image: mysql:5.7
            env:
                MYSQL_ALLOW_EMPTY_PASSWORD: yes
                MYSQL_DATABASE: wordpress
                MYSQL_USER: wordpress
                MYSQL_PASSWORD: wordpress
            ports:
                - 3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create WP Server
        uses: ./.github/actions/build-wp-container
        with:
          args: |
            PHP_VERSION=${{ matrix.php-version }}
            WP_VERSION=${{ matrix.wp-version }}
      - name: Start test server
        run: docker-compose up
      - name: Build
        run: |
          pwd
          ls
          npm -v
