name: Build And Test
on: [push, pull_request]
jobs:
  plugin:
    name: Plugin (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [7.3]
        wp-version: [5.5]
    services:
      nginx:
        # container_name: docker
        image: nginx
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Create WP Server
      #   uses: ./.github/actions/build-wp-container
        # with:
        #   args: |
        #     PHP_VERSION=${{ matrix.php-version }}
        #     WP_VERSION=${{ matrix.wp-version }}

      # see https://github.com/bahmutov/cypress-gh-action-split-install
      - run: npx cypress cache path && npx cypress cache list
      # restore / cache the binary ourselves on Linux
      # see https://github.com/actions/cache
      - name: Cache Cypress
        id: cache-cypress
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-v1-${{ runner.os }}-${{ hashFiles('**/package.json') }}
      # install Cypress binary
      - run: npx cypress install && npx cypress cache list
      - uses: cypress-io/github-action@v2
        with:
          command: npm run cy:run
          install: false
        env:
          CYPRESS_host: docker
          CYPRESS_port: 8080
