name: Build And Test
on: [push, pull_request]
jobs:
  plugin:
    name: Plugin (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [7.1]
        wp-version: [5.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: ./Dockerfile
          load: true
          build-args: |
            PHP_VERSION=${{ matrix.php-version }}
      - name: Do it
        run: |
          cd /usr/src/wordpress/
          pwd
          wp config create --dbname=$1 --dbuser=$2 --dbpass=$3 --dbhost=$4 --allow-root
          wp core install --url=http://localhost:8080 --title=Test --admin_user=$5 --admin_password=$6 --admin_email=admin@local.test --skip-email --allow-root
